### ISSUE TITLE
Add circumference=* to taginfo.json

### ISSUE THREAD

**Issue by ivanbranco** [SupaplexOSM/strassenraumkarte-neukoelln#23]
circumference=* is used to render natural=tree_stump but is not listed in the taginfo.json keys.

**Comment by tordans** [comment]
Note to self: this is the file https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/blob/main/mapstyle/taginfo/taginfo.json

**Comment by SupaplexOSM** [comment]
Thanks, I've added that - as well as a few more tags that have been added since the last map update two weeks ago (`circumference` was already missing before – thanks for noticing it!)

If anyone have an idea how to automatically create this list (e.g. from the QGIS style), please let me know - I created it manually and now have to maintain it manually when I render new features...

**Comment by SupaplexOSM** [comment]
(close)
