### ISSUE TITLE
postprocessing failing 

### ISSUE THREAD

**Issue by hb0nd** [SupaplexOSM/strassenraumkarte-neukoelln#26]
```
node/8905821518 (value of street_furniture.attribute('id'))
Traceback (most recent call last):
  File "/home/harry/Documents/Git/osm-strassenraumkarte-generator/./generate.py", line 476, in <module>
    import post_processing
  File "/usr/lib64/python3.12/site-packages/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harry/Documents/Git/osm-strassenraumkarte-generator/strassenraumkarte-neukoelln/mapstyle/post_processing.py", line 4595, in <module>
    if street_furniture.attribute('man_made') != 'guard_stone': #ausgenommen Prellsteine, die zu Einfahrten ausgerichtet werden sollen
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'man_made'
```

the node returned is a highway=street_lamp, but it fails on man_made 

location https://www.openstreetmap.org/#map=19/51.47700/0.01940

(using [mikedld/osm-strassenraumkarte-generator](https://github.com/mikedld/osm-strassenraumkarte-generator))

config.json:

```
{
  "locations": {
    "Blackheath_Standard": {
      "bbox": [51.476221,0.018282,51.478927,0.022343],
      "crs": "EPSG:25829"
    }
  }
}
```

**Comment by hb0nd** [comment]
it's now generating after disabling `STRASSENRAUMKARTE_PROC_ORIENT_MAN_MADE`

**Comment by tordans** [comment]
> the node returned is a highway=street_lamp, but it fails on man_made
> 
> location https://www.openstreetmap.org/#map=19/51.47700/0.01940

I wonder which object that might be. I see none where both tags are applied in the area https://overpass-turbo.eu/s/1MIp

**Comment by SupaplexOSM** [comment]
Oh, the error mentions `street_furniture.attribute('man_made') != 'guard_stone'`, but there is no `man_made` key in your attribute table of the "man_made" objects. May it be that your area of interest is very small and there is not a single “man_made” object [from this list](https://overpass-turbo.eu/s/1Jwo)? Then the `man_made` key is not created and the script crashes when it tries to search in it.

The script is not very robust in catching such errors so far, as there are usually enough `man_made` objects :)

A quick solution would be to remove the "guard stone" check:

```
    for street_furniture in layer_street_furniture_buffer_12.getSelectedFeatures():
        id = street_furniture.attribute('id')
        id_list_roads.append(id)
```

(What this part of the script does is to determine a direction to the nearest street for certain street furniture such as streetlights with bent masts so that they are visually oriented towards it in the rendering. That's why it crashes [on this street lamp](https://www.openstreetmap.org/node/8905821518).)

**Comment by SupaplexOSM** [comment]
Just [adjusted](https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/commit/6d0c0aa29b3d29ec32beaa6e91dd99cb7adf12fd) the processing script to prevent this error. Thanks for reporting!

**Comment by hb0nd** [comment]
thank you very much 🥰
