### ISSUE TITLE
Sidewalks, Crossings

### ISSUE THREAD

**Issue by hungerburg** [SupaplexOSM/strassenraumkarte-neukoelln#3]
How about rendering sidewalks that are properties of a street? There is an overlay for that here https://osm-tiles.james-ross.co.uk/?map=19/52.4758/13.4336&layer=standard&layer=roads - but it seems broken at the moment - this also should render parking lanes, so it is in a way similar to your map, though not so advanced.

In the same way, it would be nice to visualize zebra crossings, OSM France does that, even including tactile pavings, but it is broken too - they show a "crossing=no" as a zebra…

EDIT: Link zu James Ross Karte aktualisiert

**Comment by tordans** [comment]
> rendering sidewalks that are properties of a street

AFAIK that has not been a priority, yet. One advantage of having this project only in this very small area is, that Alex can base the rending on micro mapping that is not available everywhere. It's also one of our goals to experiment with micro mapping and while doing that to develop guidelines and tags that work well for this kind of mapping.

> it would be nice to visualize zebra crossings

The "Straßenraumkarte" AKA micromap does render `crossing=zebra`, eg. https://supaplexosm.github.io/strassenraumkarte-neukoelln/?map=micromap#20/52.47581/13.43357

**Comment by hungerburg** [comment]
Well, it is your map, you may omit whatever you please; I just thought, sidewalks are part of the street, so why not show them in a Straßenraumkarte? Especially, as parking lanes mapped as properties of a street show, if I fully understand.

The zebra crossings I still do not see, perhaps its the two thin lines, aka casing of the crossing footway?

**Comment by tordans** [comment]
>  sidewalks are part of the street, so why not show them in a Straßenraumkarte

It does show them, but only if they are mapped as separate ways. Which is something we are working on: Collect feedback on how separately mapped sidewalks (and bike lanes) can be done well …

Example: https://supaplexosm.github.io/strassenraumkarte-neukoelln/?map=micromap#20/52.48168/13.44006

![image](https://user-images.githubusercontent.com/111561/136557779-c8496b6f-88c7-4885-9ab1-5ac513605667.png)

> The zebra crossings I still do not see

[A good example](https://supaplexosm.github.io/strassenraumkarte-neukoelln/?map=micromap#20/52.47582/13.43368): 

![image](https://user-images.githubusercontent.com/111561/136557950-b03cbf92-480d-43af-b363-c0a739687c9c.png)


And one that shows a bug, where the parking lane line has not been split automatically :-).

![image](https://user-images.githubusercontent.com/111561/136557883-9ad15edc-84a9-4067-a203-415253b86009.png)

**Comment by SupaplexOSM** [comment]
The micro map/Straßenraumkarte is based on the very precise location of objects and paths in space and aims to show exact relations between e.g. the kerb line and objects "on" the kerb. I am afraid that this claim is incompatible with a generalised rendering of sidewalk information from highway lines, because even if we measured the exact street/carriageway widths, the location of the sidewalks would always only be a rough approximation and often the sidewalks would be located somewhere "beside" the actual location.

This is also the reason why the parking lanes are not generated 1 to 1 from the OSM data, but we have created a separate, manually readjusted parking lane layer for this purpose (the parking lanes were snapped to the kerbs in a semi-automated way and were manually readjusted).

@tordans: your links seem to be broken - instead, the map section always jumps to the default coordinate :(

@third picture with zebra stripes: These are temporary zebra crossings during construction works - I usually don't adjust the parking lanes for temporary changes... Maybe I should do that here exceptionally, since the construction site will probably last longer :)

**Comment by tordans** [comment]
> your links seem to be broken - instead, the map section always jumps to the default coordinate :(

Wow, that bug took me down a rabbit whole 😄 . Found a fix, though 💪  (see https://github.com/mlevans/leaflet-hash/issues/56).
The links from above are working now and the UX is improved a bit for switching the map via the primary navigation.

**Comment by tordans** [comment]
> These are temporary zebra crossings during construction works

Idea: Maybe you could color the construction segments (like the zebra, but maybe even the whole construction-crossing) differently (yellow, which would even be true to reality in most cases) and once we have a legend, we could explain it there.

**Comment by SupaplexOSM** [comment]
I'll close this. To render sidewalks on this kind of map, they need to be mapped separately, since it's otherwise not possible to derive their exact location in this map style, which is designed to be area-based. Temporary lines are now shown in yellow.
